services:
  namenode:
    build: ./NameNode
    container_name: namenode
    ports:
      - "9870:9870"
    volumes:
      - namenode_data:/usr/local/app/namenode_metadata
      - namenode_logs:/usr/local/app/namenode_logs
      - namenode_block_logs:/usr/local/app/namenode_block_logs
    environment:
      - BLOCK_SIZE_BYTES=33554432
      - REPLICATION_FACTOR=2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9870/health"]
      interval: 5s
      timeout: 1s
      retries: 5
    networks:
      - hadoop-net

  datanode:
    build: ./DataNode
    volumes:
      - datanode_data:/usr/local/app/data
    depends_on:
      namenode:
        condition: service_healthy
    networks:
      - hadoop-net

  client:
    build: ./Client
    volumes:
      - ./client_testfiles:/app/client_testfiles
    depends_on:
      namenode:
        condition: service_healthy
    networks:
      - hadoop-net

networks:
  hadoop-net:
    driver: bridge

volumes:
  namenode_data:
  namenode_logs:
  namenode_block_logs:
  datanode_data:
